#!/usr/bin/env bash
# preprocess bats source file STDIN into a bash runable script STDOUT
# unittest: OK ../test/internal/bats-preprocess_unit.bats
# fonctionnal test: ../test/internal/bats-preprocess.bats
#
# Usage: ./bats-preprocess < INUPT.bats > OUTPUT.sh

encode_name() {
  local name="$1"
  local result="test_"
  local hex_code

  if [[ ! "$name" =~ [^[:alnum:]\ _-] ]]; then
    name="${name//_/-5f}"
    name="${name//-/-2d}"
    name="${name// /_}"
    result+="$name"
  else
    local length="${#name}"
    local char i

    for ((i=0; i<length; i++)); do
      char="${name:$i:1}"
      if [ "$char" = " " ]; then
        result+="_"
      elif [[ "$char" =~ [[:alnum:]] ]]; then
        result+="$char"
      else
        printf -v 'hex_code' -- "-%02x" \'"$char"
        result+="$hex_code"
      fi
    done
  fi

  printf -v "$2" '%s' "$result"
}

main() {
  local tests=()
  local index=0
  local line body test_name index encoded_name

  if [[ -z "BATS_TEST_PATTERN" ]] ; then
    BATS_TEST_PATTERN='^ *@test +(.+) +\{ *(.*)$'
  fi

  while IFS= read -r line; do
    line="${line//$'\r'}"
    let index+=1
    if [[ "$line" =~ $BATS_TEST_PATTERN ]]; then
      name="${BASH_REMATCH[1]#[\'\"]}"
      name="${name%[\'\"]}"
      body="${BASH_REMATCH[2]}"
      encode_name "$name" 'encoded_name'
      tests["${#tests[@]}"]="$encoded_name"
      echo "${encoded_name}() { bats_test_begin \"${name}\" ${index}; ${body}"
    else
      printf "%s\n" "$line"
    fi
  done

  for test_name in "${tests[@]}"; do
    echo "bats_test_function ${test_name}"
  done
}

[[ $0 != "$BASH_SOURCE" ]] && sourced=1 || sourced=0
if [[ $sourced -eq 0  ]] ; then 
  # exit on fail
  set -e
  main "$@"
fi
