#!/bin/bash
#
# run make before is this code has changed

tmp=tmp-bats-preprocess
BPP=../../libexec/bats-preprocess

test_preprocess_myself() { bats_test_begin "preprocess myself" 8; 
  cat $BATS_TEST_FILENAME | $BPP > $tmp
  diff -q $tmp out
}

test_dummy_test() { bats_test_begin "dummy test" 13; 
  echo ok
}
bats_test_function test_preprocess_myself
bats_test_function test_dummy_test
