#!/bin/bash
#
# run make before, if this code has changed
#

BPP=../../libexec/bats-preprocess
cd $BATS_TEST_DIRNAME

test_preprocess_myself() { bats_test_begin "preprocess myself" 9; 
  diff -u <( $BPP < $BATS_TEST_FILENAME ) out
}

test_dummy_test() { bats_test_begin "dummy test" 13; 
  echo ok
}
bats_test_function test_preprocess_myself
bats_test_function test_dummy_test
